# Generated by Django 5.2.7 on 2025-11-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_booked',
        ),
    ]
